tech:
  pyloncompass:
    type: PYLONFINDER
    show_non_running: true
    show_upgrading: true
    update_cooldown: 5s
    tag:
      type: LORE
      lore: Inactive and Upgrading Pylons
      material: COMPASS
  leafshears:
    type: LEAFSHEARS
    clear_cube_size: 3
    cannot_bypass_message: "&cSome of leaves are reinforced and therefore cannot be broken. Please use another tool to break it."
    durability_loss_chance: 0.1
    tag:
      type: LORE
      lore: Leaf Shears
      material: SHEARS
anvil:
  repairMaterials:
    emerald:
      item:
        material: EMERALD
      value: 1.0
    emeraldblock:
      item:
        material: EMERALD_BLOCK
      value: 9.0
  materialCosts:
    diamondPick:
      material: DIAMOND_PICKAXE
      value: 15
    diamondSword:
      material: DIAMOND_SWORD
      value: 10
    diamondShovel:
      material: DIAMOND_SPADE
      value: 5
    diamondAxe:
      material: DIAMOND_AXE
      value: 15
    diamondHoe:
      material: DIAMOND_HOE
      value: 10
    diamondHelmet:
      material: DIAMOND_HELMET
      value: 25
    diamondChest:
      material: DIAMOND_CHESTPLATE
      value: 40
    diamondLeggings:
      material: DIAMOND_LEGGINGS
      value: 35
    diamondBoots:
      material: DIAMOND_BOOTS
      value: 20
    ironPick:
      material: IRON_PICKAXE
      value: 6
    ironSword:
      material: IRON_SWORD
      value: 4
    ironShovel:
      material: IRON_SPADE
      value: 2
    ironAxe:
      material: IRON_AXE
      value: 6
    ironHoe:
      material: IRON_HOE
      value: 4
    ironHelmet:
      material: IRON_HELMET
      value: 10
    ironChest:
      material: IRON_CHESTPLATE
      value: 16
    ironLeggings:
      material: IRON_LEGGINGS
      value: 14
    ironBoots:
      material: IRON_BOOTS
      value: 8
  enchantCosts:
        fireprot:
          enchant: PROTECTION_FIRE
          value: 3
        flame:
          enchant: ARROW_FIRE
          value: 19
        fireaspect:
          enchant: FIRE_ASPECT
          value: 11
        depthstrider:
          enchant: DEPTH_STRIDER
          value: 5
        respiration:
          enchant: OXYGEN
          value: 4
        frostwalker:
          enchant: FROST_WALKER
          value: 12
        aquaafinity:
          enchant: WATER_WORKER
          value: 6
        featherfalling:
          enchant: PROTECTION_FALL
          value: 4
        baneofarthropods:
          enchant: DAMAGE_ARTHROPODS
          value: 3
        infinity:
          enchant: ARROW_INFINITE
          value: 19
        silktouch:
          enchant: SILK_TOUCH
          value: 12
        protection:
          enchant: PROTECTION_ENVIRONMENTAL
          value: 3
        blastprotection:
          enchant: PROTECTION_EXPLOSIONS
          value: 1
        thorns:
          enchant: THORNS
          value: 2
        power:
          enchant: ARROW_DAMAGE
          value: 8
        projectileprotection:
          enchant: PROTECTION_PROJECTILE
          value: 1
        punch:
          enchant: ARROW_KNOCKBACK
          value: 7
        sharpness:
          enchant: DAMAGE_ALL
          value: 8
        smite:
          enchant: DAMAGE_UNDEAD
          value: 3
        knockback:
          enchant: KNOCKBACK
          value: 7
        efficiency:
          enchant: DIG_SPEED
          value: 1
        unbreaking:
          enchant: DURABILITY
          value: 3
  renamingCost: 2.0
  scaleWithMissingDura: true
  blacklistedLore:
   - Compacted Item
